version: 0.0
os: linux
files:
  - source: /app.wsgi
    destination: /var/www/guestbook-app
  - source: /
    destination: /home/ec2-user/guestbook-app
  - source: /conf/guestbook_app.conf
    destination: /etc/httpd/conf.d
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
