version: 0.0
os: linux
files:
  - source: /app.wsgi
    destination: /var/www/pythonmysql
  - source: /
    destination: /home/ec2-user/pythonmysql
  - source: /conf/pythonmysql.conf
    destination: /etc/httpd/conf.d
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
