version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/pythonmysql
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    
hooks:
  ApplicationStart:
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root
