version: 0.0
os: linux
files:
  - source: /guestapp-python-redis-mysql-docker-k8s
    destination: /home/ec2-user/pythonmysql
  - source: /guestapp-python-redis-mysql-docker-k8s/scripts
    destination: /home/ec2-user/pythonmysql/scripts
    
   
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    
hooks:
  ApplicationStart:
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root
