version: 0.2

env:
  variables:
     # key: "value"
     # key: "value"
     MYSQL_USER: "admin"	
     MYSQL_HOST:	"db1.cdcey7nbdoev.us-east-1.rds.amazonaws.com"	
     MYSQL_PASSWORD:	"admin123"	
     MYSQL_ROOT_PASSWORD: "admin123"	
     db_port: "3306"	
     MYSQL_DATABASE: "mysql"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      # name: version
      # name: version
      python: 3.8
    #commands:
      # - command
      # - command
    pre_build:
     commands:
      # - command
       - command
         - pip3 install -y requirements.txt  
  build:
    commands:
      # - command
      #  - command
      #    - export FLASK_APP = app.py
           - echo 'successfully installed'
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
   files:
     - '**/*' 
    # - location
    # - location
   name: BuildArtifact
   discard-paths: no
   base-directory: guestbook-app
#cache:
  #paths:
    # - paths
